SRCFILE = /1202prj/nio_source/top/nio_top_manifest.v
OPTIONS = -I /1202prj/common/hss_share/aec_revise -I /1202prj/common/pcs25g/std_ovl -I /1202prj/nio_source/ei/source/pciexg3/pciexg3utl_v001/verilog/rtl -I /1202prj/nio_source/ei/source/pciexg3/pciexg3cfg_v001/verilog/rtl -I /1202prj/testbench/ei_tb/testbench/pciexg3/pciexg3cfg_v001/verilog/rtl -I /1202prj/nio_source/ei/source/pciexg3/pciexg3pipepcs_v006/verilog/rtl -I /1202prj/testbench/ei_tb/testbench/pciexg3/pciexg3tldlp_v001/verilog/rtl  -I /1202prj/testbench/ei_tb/testbench/pciexg3 -I /1202prj/nio_source/ei/source/pciexg3 -I /1202prj/testbench/ei_tb/testbench/pciexg3/pciexg3utl_v001/verilog/rtl -I /1202prj/nio_source/ei/source/pciexg3/pciexg3tldlp_v001/verilog/rtl


include ../scr/Makefile.include

