# $^ all depende files
# $< first depend file
# $@ target file

all : sdf.v


step1 : noinclude.v
step2 : nodef.v
step3 : sdf.v

sdf.v : nodef.v
	checker $< > $@ 2>error3

nodef.v : noinclude.v
	step2_nodef $< > $@ 2>error2

noinclude.v : ${SRCFILE}
	step1_noinc_comment $< ${OPTIONS} > $@ 2>error1
	
sdf.v.new : sdf.v
	../scr/vtran.scr $<

nodef.v.new : nodef.v
	../scr/vtran.scr $<

check : sdf.v.new nodef.v.new
	diff sdf.v.new nodef.v.new |grep -v "\`line"|grep -v "[0-9]\+[ad][0-9]\+"|more

clean :
	rm -f *.v error* *.v.add *.v.new
