# $^ all depende files
# $< first depend file
# $@ target file
# $?  all the prerequisites that are newer than the target

.PHONY: clean
.PHONY: test
.PHONY: test_ivlpp


#step1 to 3 of my prpgram
sdf.v : nodef.v
	checker $< > step3.v 2>>error
	mv step3.v $@

nodef.v : ${SRCFILE}
	step2_nodef $<  ${OPTIONS} > step2.v 2>>error
	mv step2.v $@

#noinclude.v : ${SRCFILE}
#	step1_noinc_comment $< ${OPTIONS} > step1.v 2>error
#	mv step1.v $@

# tokenrize parser result and step2 result
sdf.v.tok : sdf.v
	tok.sh $<

nodef.v.tok : nodef.v
	tok.sh $<

# trying ivlpp to generate its tokenrize file
ivlpp.v : $(SRCFILE)
	genivlppcfg ${OPTIONS} > cfg
	ivlpp -L -F cfg $< > ivlpp.v

ivlpp.v.noinc : ivlpp.v
	step1_noinc_comment $< > ivlpp.v.noinc

ivlpp.v.noinc.tok : ivlpp.v.noinc
	tok.sh $<

test : sdf.v.tok nodef.v.tok 
	# comparing before and after checher
	- diff sdf.v.tok nodef.v.tok  > diff_parse
	# comparing after checker with previous run
	cp std/sdf.v old.v
	- tok.sh old.v
	- diff sdf.v.tok old.v.tok > diff_2old

test_ivlpp :sdf.v.tok ivlpp.v.noinc.tok
	# comparing after checher and ivlpp
	- diff sdf.v.tok ivlpp.v.noinc.tok > diff_2ivl

clean :
	rm -f *.v error* *.v.add *.v.new diff_* ivlpp* *.tok *cfg*
	rm -rf INCA_libs/ irun.log

