# $^ all depende files
# $< first depend file
# $@ target file
# $?  all the prerequisites that are newer than the target

.PHONY: build
.PHONY: clean
.PHONY: test

build : sdf.v

sdf.v : nodef.v
	checker $< > step3.v 2>>error
	mv step3.v $@

nodef.v : noinclude.v
	step2_nodef $< > step2.v 2>>error
	mv step2.v $@

noinclude.v : ${SRCFILE}
	step1_noinc_comment $< ${OPTIONS} > step1.v 2>error
	mv step1.v $@
	
sdf.v.new : sdf.v
	../scr/vtran.scr $<

nodef.v.new : nodef.v
	../scr/vtran.scr $<

test : sdf.v.new nodef.v.new
	- diff sdf.v.new nodef.v.new |grep -v "\`line"|grep -v "[0-9]\+[ad][0-9]\+" > diff_parse
	- diff sdf.v std/sdf.v > diff_2old

clean :
	rm -f *.v error* *.v.add *.v.new diff_*


